version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-util
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-util-{{ checksum "gradle.properties" }}
            - eventuate-util-
      - run: TERM=dumb ./gradlew testClasses aggregateJavaDocs
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-util-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew build
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context:
            - publish
